#Accelerometers
accelerometer_noise_density: 1.7834838308e-02   #Noise density (continuous-time)
accelerometer_random_walk:   8.0713144126e-04   #Bias random walk

#Gyroscopes
gyroscope_noise_density:     1.6684393481e-03   #Noise density (continuous-time)
gyroscope_random_walk:       1.0145681918e-04   #Bias random walk

rostopic:                    /imu0      #the IMU ROS topic
update_rate:                 200.0       #Hz (for discretization)
