#Accelerometers
accelerometer_noise_density: 1.6466848943e-02   #Noise density (continuous-time)
accelerometer_random_walk:   6.4051996295e-04   #Bias random walk

#Gyroscopes
gyroscope_noise_density:     1.5060611666e-03   #Noise density (continuous-time)
gyroscope_random_walk:       8.0837533667e-05   #Bias random walk

rostopic:                    /imu0      #the IMU ROS topic
update_rate:                 200.0       #Hz (for discretization)