#Accelerometers
accelerometer_noise_density: 1.7723688651e-02   #Noise density (continuous-time)
accelerometer_random_walk:   7.5311595246e-04   #Bias random walk

#Gyroscopes
gyroscope_noise_density:     1.4330686161e-03   #Noise density (continuous-time)
gyroscope_random_walk:       5.8000808454e-05   #Bias random walk

rostopic:                    /imu0      #the IMU ROS topic
update_rate:                 200.0       #Hz (for discretization)
